config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  get 'welcome/index'

  resources :pedidos
  resources :produtos
  resources :usuarios

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many(:pedidos)
  validates :cpf, presence: { message: "nao deve ser em branco"},
              length: { is:11, message:"deve ter 11 digitos"},
              numericality: { only_integer:true,message:"deve conter apenas números" }
  validates :nome, presence: {message: " nao deve ser em branco" },
              length: {minimum: 5,too_short: "deve ter pelo menos 5 caracteres" }
  validates :telefone, presence: {message: " nao deve ser em branco" },
              length: {minimum: 8,too_short: "deve ter pelo menos 8 caracteres" },
              numericality: {only_integer:true,message:"deve conter apenas números"}
  validates :rua, presence: {message: " nao deve ser em branco" },
              length: {minimum: 8,too_short: "deve ter pelo menos 8 caracteres" }
  validates :numero, presence: {message: " nao deve ser em branco" },
              numericality: {only_integer:true,message:"deve conter apenas números"}
  validates :bairro, presence: {message: " nao deve ser em branco" },
              length: {minimum: 4,too_short: "deve ter pelo menos 4 caracteres" }
  validates :cidade, presence: {message: " nao deve ser em branco" },
              length: {minimum: 3,too_short: "deve ter pelo menos 3 caracteres" }
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:cpf, :nome, :telefone, :rua, :numero, :bairro, :cidade)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :cliente_cpf %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :cliente_nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :cliente_telefone %>
  </div>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :rua, id: :cliente_rua %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :cliente_numero %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :cliente_bairro %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :cliente_cidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Cpf</th>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Rua</th>
      <th>Numero</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.rua %></td>
        <td><%= cliente.numero %></td>
        <td><%= cliente.bairro %></td>
        <td><%= cliente.cidade %></td>
        <td><%= link_to 'Visualizar', cliente, id: "v-#{cliente.cpf}" %></td>
        <td><%= link_to 'Alterar', edit_cliente_path(cliente), id: "e-#{cliente.cpf}" %></td>
        <td><%= link_to 'Deletar', cliente, method: :delete, id: "d-#{cliente.cpf}"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<p>
  <strong>Rua:</strong>
  <%= @cliente.rua %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @cliente.numero %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @cliente.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cliente.cidade %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>