config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  get 'welcome/index'

  resources :pedidos
  resources :produtos
  resources :usuarios

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/produto.rb
class Produto < ApplicationRecord

  validates :codigo, presence: { message: "deve ser preenchido"}
  validates :nome, presence: { message: "deve ser preenchido"}
  validates :valor, presence: { message: "deve ser preenchido"}

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
    @produtos = Produto.all
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso!' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto alterado com sucesso!' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:codigo, :nome, :valor)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.number_field :codigo, id: :produto_codigo %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :produto_nome %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :produto_valor %>
  </div>

  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Alterar Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Vizualizar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nome</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.codigo %></td>
        <td><%= produto.nome %></td>
        <td><%= produto.valor %></td>
        <td><%= link_to 'Vizualizar', produto, id:"v-#{produto.nome}" %></td>
        <td><%= link_to 'Alterar', edit_produto_path(produto), id: "e-#{produto.nome}"%></td>
        <td><%= link_to 'Remover', produto, method: :delete, id:"r-#{produto.nome}"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @produto.codigo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto.valor %>
</p>

<%= link_to 'Alterar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>