config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  get 'welcome/index'

  resources :pedidos
  resources :produtos
  resources :usuarios

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord

  has_many(:pedidos)
  validates :cpf, presence: { message: "nao deve ser em branco"},
            length: { is:11, message:"deve ter 11 digitos"},
            numericality: { only_integer:true,message:"deve conter apenas numeros" }
  validates :nome, presence: {message: " nao deve ser em branco" },
            length: {minimum: 5,too_short: "deve ter pelo menos 5 caracteres" }
  validates :login, presence: {message: " nao deve ser em branco" },
            length: {minimum: 5,too_short: "deve ter pelo menos 5 caracteres" }
  validates :senha, presence: {message: " nao deve ser em branco" },
            length: {minimum: 5,too_short: "deve ter pelo menos 5 caracteres" }
  validates :cargo, presence: {message: " nao deve ser em branco" },
            length: {minimum: 5,too_short: "deve ter pelo menos 5 caracteres" }

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario criado com sucesso!' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario alterado com sucesso!' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :cpf, :login, :senha, :cargo)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :usuario_nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :usuario_cpf %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :usuario_login %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha, id: :usuario_senha %>
  </div>

  <div class="field">
    <%= form.label :cargo %>
    <%= form.text_field :cargo, id: :usuario_cargo %>
  </div>

  <div class="actions">
    <%= form.submit value= 'Criar Usuario'%>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Alterar Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Vizualizar', @usuario %> |
<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Login</th>
      <th>Senha</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.cpf %></td>
        <td><%= usuario.login %></td>
        <td><%= usuario.senha %></td>
        <td><%= usuario.cargo %></td>
        <td><%= link_to 'Vizualizar', usuario, id: "v-#{usuario.cpf}"%></td>
        <td><%= link_to 'Alterar', edit_usuario_path(usuario), id: "e-#{usuario.cpf}" %></td>
        <td><%= link_to 'Remover', usuario, method: :delete, id:"r-#{usuario.cpf}"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Novo Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @usuario.cpf %>
</p>

<p>
  <strong>Login:</strong>
  <%= @usuario.login %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @usuario.senha %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @usuario.cargo %>
</p>

<%= link_to 'Alterar', edit_usuario_path(@usuario) %> |
<%= link_to 'Voltar', usuarios_path %>